### ISSUE TITLE
Acceleration.BaseDimensions.IsBaseQuantity() returns true

### ISSUE THREAD

**Issue by lipchev** [angularsen/UnitsNet#1442] opened 2024-12-04 23:46 UTC
**Describe the bug**
The [`BaseDimensions.IsBaseQuantity()`](https://github.com/angularsen/UnitsNet/blob/b57ac63dc5cfe7b9cda21c5451ca72bbf7f598dc/UnitsNet/BaseDimensions.cs#L31) function filters out all dimensions that are <> 1, before taking the count- which is incorrect for something like the `Acceleration` with it's dimensions of `[1, 0, -2, 0, 0, 0, 0]`.

**To Reproduce**
`Acceleration.BaseDimensions.IsBaseQuantity()`

**Comment by angularsen** [comment] 2024-12-07 16:36
I believe this is a duplicate of https://github.com/angularsen/UnitsNet/pull/1430

**Closed by angularsen** 2024-12-07 16:36 UTC
Labels: bug

**Comment by lipchev** [comment] 2024-12-11 16:07
@angularsen  Note that only the "Fix a bug in BaseDimensions.ToString() (#1431)" has been carried over into v6, the `IsBaseQuantity` was not. I'm going to create another PR for v6 - I think my version of the fix is slightly better.

**Comment by lipchev** [comment] 2024-12-11 16:43
Oh, i see- this was only fixed 4 days ago- I thought that both issues were from months ago..
