### ISSUE TITLE
Support for non-number values for double

### ISSUE THREAD

**Issue by ebfortin** [angularsen/UnitsNet#695] opened 2019-08-18 14:07 UTC
**Is your feature request related to a problem? Please describe.**
In the framework I'm working on and using UnistNet with, I came into a situation where I get Inifinity for a calculation. Infinity is something that is totally valid for what I'm doing. However, there is a systematic check of NaN and Inifinity in UnitsNet that makes these "values" impossible to use.

**Describe the solution you'd like**
I would like to have non-numbers values of double to be permitted. Or at least an option to have the check disabled.

**Describe alternatives you've considered**
Currently I'm using double.MaxValue for infinity and double? for situation where I have something not applicable, something I used to signal with NaN. It creates more code. 

**Additional context**
N/A

**Comment by angularsen** [comment] 2019-08-18 15:09
This is by design. Primarily because we currently have `decimal` in a handful of quantities and that number type does not support infinity nor NaN, so we want the behavior to be consistent for all quantities.

We can reconsider if we change to support any numeric type and that pretty much requires changing from `struct` to `class` first to support generics and avoid explosion of method overloads. I think we will get there someday, but no one is currently pushing for it.  

@tmilnthorp I know you had great interest in moving to `class`, just wanted to let you know that I've started leaning towards that being a good idea since there are some significant gains there, I just don't have the time or interest to pursue it myself. Let me know if you want to start that work.

https://github.com/angularsen/UnitsNet/issues?utf8=%E2%9C%93&q=nan

**Comment by ebfortin** [comment] 2019-08-18 15:12
I'm not sure going to class is a good idea. All these values are really value types. So they should, I think, stay as struct. If it means having the same architecture as today, I'm fine with it.

**Comment by angularsen** [comment] 2019-08-18 17:07
I'm with you on the drawbacks of going to `class`. Semantically changing from value types to reference types, and the whole "can be null" semantics is something I truly feel is a misfit for our quantity types and why I argued against it in the first place. 

However, it does add two major benefits; inheritance and generics. This will allow us to let the user choose whether to use `float`, `double` or `decimal` as backing type without having 3x quantity types and methods. Binary size is arguably a concern to some people when we start to generate so much code like we do. It also solves the whole "some quantities using `decimal` internally, while most others use `double`".

I'm still kind of split on this, but I think I'm willing to give `class` at least a try and play with it for some time and see how it feels before deciding finally.

**Comment by ebfortin** [comment] 2019-08-18 17:54
What are the limitation for generics usage with structs? I can't find any reference that state hard limitations. Or maybe I just didn't a thorough enough search.

**Comment by angularsen** [comment] 2019-08-18 19:46
Uhm, I can't seem to recall exactly the limitation we hit. I believe it had something to do with using generics to generalize arithmetic across any numeric type and for some reason that was not possible with `struct`. Or maybe I am mixing things up, it's been so long since we last discussed and I didn't do the research myself.

I did a quick naive test just now and my first stumbling block is instantiating the generic types, and it's not related to `struct` really. Am I thinking about it all wrong? Is there a better way to do this? Neither of the below two approaches seem appealing due to boxing or reflection overhead.

```c#
void Main()
{
	Foo<float>.AddWithObjectBoxing(new Foo<float>(1), new Foo<float>(2)).Value.Dump("AddWithObjecBoxing: This should be 3");
	Foo<float>.AddWithDynamic(new Foo<float>(1), new Foo<float>(2)).Value.Dump("AddWithDynamic: This should be 3");
}

public struct Foo<T> where T : struct
{
	public T Value;
	public Foo(T val)
	{
		Value = val;
	}
	
	public static Foo<T> AddWithObjectBoxing(Foo<T> a, Foo<T> b) {
		if (a.Value is float aFloatValue && b.Value is float bFloatValue)
			return new Foo<T>((T)(object)(aFloatValue + bFloatValue));
			
		throw new NotImplementedException();
	}

	public static Foo<T> AddWithDynamic(Foo<T> a, Foo<T> b)
	{
		return new Foo<T>(((dynamic)a.Value) + ((dynamic)b.Value));
	}
}
```

**Comment by angularsen** [comment] 2019-08-18 19:49
@zacharypatten earlier brought to our attention how to do arithmetics with generics in a performant way using runtime compilation. It sounds super interesting and I'd look closer at how he did that and try to learn from him.

https://github.com/angularsen/UnitsNet/issues/666#issuecomment-490654358

**Comment by ebfortin** [comment] 2019-08-18 20:33
I don't understand why there is boxing in your example since T is constrained to a struct. I'll do some test myself as well. Would be great to have generics AND keep structs!

**Comment by ebfortin** [comment] 2019-08-18 20:43
Interesting question on the subject : https://social.msdn.microsoft.com/Forums/en-US/d2aa3b06-c55b-4b22-a4ea-61c9d54db8b7/operators-in-generic-interface?forum=csharplanguage

**Comment by ZacharyPatten** [comment] 2019-08-18 20:57
There is a new feature proposed for C# 9.0 currently called "Shapes"
https://github.com/dotnet/csharplang/issues/110

That will allow for zero overhead generic mathematics. However, that is a long way off (and is only a candidate feature for C# 9.0 so it is not set in stone). Also, "Shapes" would not 100% obsolete runtime compilation. Using runtime compilation you can optimize code for specific types, but you lose that ability when you use Shapes (I can elaborate on this topic if you would like).

Interfacing is a bad solution. If you want to go interfacing rather than runtime compilation, you might as well wait until C# 9.0 so you can use Shapes.

Also... If done right, the runtime compilation code will be very similar to the Shapes code when C# 9.0 comes, so it will be an easy transition (mostly just adding in the shapes as generic constraints).

So I still recommend my comments from the other issue. Runtime compilation is currently the best option.

**Comment by ebfortin** [comment] 2019-08-31 12:51
The 2-3x penality on performance is probably because the compiler is able to inline the call to operator+ when it's a double. I wonder how we could help the compiler inline AdditionExpression. Or the JIT later at runtime. I wonder also if contraining T to a value type (struct) would help with code optimisation at compile time and runtime.

**Comment by ZacharyPatten** [comment] 2019-08-31 13:21
@ebfortin There might be a little room for optimization, but that is about as good as we will be able to do unti if/when "Shapes" are added (aka type classes) to C#. It is scheduled for C# 9. Shapes allow for zero overhead generic mathematics because it takes advantage of inlining that occurs on struct generics.

So the answer to your "I wonder if..." is Shapes in C# 9.

**Comment by ebfortin** [comment] 2019-09-17 21:16
I got some good results by adding MethodImpl(MethodImplOptions.AggressiveOptimization) to the operator method. About 30%. AggressiveInlining did no change.

I would want to look at the x86 code produced to compare. Anyone have a good extensions to do that?

**Comment by ZacharyPatten** [comment] 2019-09-18 16:52
I just want to note that Shapes or "Type Classes" got pushed back till at least C# 10 (I was under the impression it would be in C# 9)... :( So it will take a long time for that to be a feature in C#

**Closed** 2019-11-24 18:17 UTC
Labels: enhancement, wontfix
