### ISSUE TITLE
Precision error when calculating small volumes

### ISSUE THREAD

**Issue by mortenbock** [angularsen/UnitsNet#1199] opened 2023-02-10 15:45 UTC
**Describe the bug**
Given this unit test:

    [Test]
    public void Foo()
    {
        Length length = Length.FromMillimeters(10);
        Length width = Length.FromMillimeters(10);
        Length height = Length.FromMillimeters(10);

        Volume volume = length * width * height;

        Assert.That(volume.CubicMillimeters, Is.EqualTo(1000));
    }

The test fails with:

    Expected: 1000
    But was:  1000.0000000000001d

It seems that working with small units means that the precision of the calculations are not correct?

Using version 5.1.0

**Comment by angularsen** [comment] 2023-02-12 12:07
Duplicate of #1193, please continue the discussion there.

**Closed by angularsen** 2023-02-12 12:07 UTC
Labels: bug

**Comment by angularsen** [comment] 2023-02-12 12:11
Actually, your question is not the exact same issue as 1193 since it does not involve units in the equality, so I will answer here.

This is generally due to `double` precision in arithmetic, you can't assume it will always be perfectly 1000. When comparing `double` values, you should always specify a max error tolerance. Most unit test frameworks provide this or you can write your own.

For example, FluentAssertions has `value.Should().BeApproximately(3.14F, 0.01F);`
